USE DATABASE CEDP_HCP_OUTREACH;
USE SCHEMA BRONZE;
USE WAREHOUSE CEDP_ETL_WH;

CREATE TABLE IF NOT EXISTS RAW_HCP_SUBSCRIBER (
    SUBSCRIBER_KEY      VARCHAR,
    NPI                 VARCHAR,
    FIRST_NAME          VARCHAR,
    LAST_NAME           VARCHAR,
    SPECIALTY           VARCHAR,
    HCP_TIER            VARCHAR,
    LICENSE_STATE       VARCHAR,
    INSTITUTION_NAME    VARCHAR,
    CONSENT_STATUS      VARCHAR,
    DO_NOT_CONTACT_FLAG VARCHAR,
    BUSINESS_UNIT_ID    VARCHAR,
    BRAND_ID            VARCHAR,
    IMPORT_DATE         VARCHAR,
    SOURCE_FILE_NAME    VARCHAR,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_HCP_SUBSCRIBER
    (SUBSCRIBER_KEY, NPI, FIRST_NAME, LAST_NAME, SPECIALTY, HCP_TIER, LICENSE_STATE,
     INSTITUTION_NAME, CONSENT_STATUS, DO_NOT_CONTACT_FLAG, BUSINESS_UNIT_ID, BRAND_ID,
     IMPORT_DATE, SOURCE_FILE_NAME)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, METADATA$FILENAME
    FROM @STG_HCP_LANDING/hcp_subscribers.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_AUTOMATION_ACTIVITY_LOG (
    AUTOMATION_NAME       VARCHAR,
    ACTIVITY_NAME         VARCHAR,
    ACTIVITY_TYPE         VARCHAR,
    TARGET_DATA_EXTENSION VARCHAR,
    SQL_TEXT              VARCHAR,
    RUN_ID                VARCHAR,
    INPUT_COUNT           NUMBER,
    OUTPUT_COUNT          NUMBER,
    EXCLUDED_COUNT        NUMBER,
    RUN_TIMESTAMP         TIMESTAMP_NTZ,
    LOAD_TIMESTAMP        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_AUTOMATION_ACTIVITY_LOG
    (AUTOMATION_NAME, ACTIVITY_NAME, ACTIVITY_TYPE, TARGET_DATA_EXTENSION, SQL_TEXT,
     RUN_ID, INPUT_COUNT, OUTPUT_COUNT, EXCLUDED_COUNT, RUN_TIMESTAMP)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, TO_TIMESTAMP_NTZ($10)
    FROM @STG_HCP_LANDING/sfmc_automation_studio_activity_log.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_JOURNEY_STATUS (
    SUBSCRIBER_KEY   VARCHAR,
    JOURNEY_NAME     VARCHAR,
    JOURNEY_VERSION  VARCHAR,
    JOURNEY_STATUS   VARCHAR,
    ENTRY_TIMESTAMP  TIMESTAMP_NTZ,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_JOURNEY_STATUS
    (SUBSCRIBER_KEY, JOURNEY_NAME, JOURNEY_VERSION, JOURNEY_STATUS, ENTRY_TIMESTAMP)
FROM (
    SELECT $1, $2, $3, $4, TO_TIMESTAMP_NTZ($5)
    FROM @STG_HCP_LANDING/sfmc_journey_status.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_LISTSUBSCRIBERS (
    SUBSCRIBER_KEY  VARCHAR,
    LIST_ID         VARCHAR,
    LIST_STATUS     VARCHAR,
    STATUS_REASON   VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_LISTSUBSCRIBERS (SUBSCRIBER_KEY, LIST_ID, LIST_STATUS, STATUS_REASON)
FROM (
    SELECT $1, $2, $3, $4
    FROM @STG_HCP_LANDING/sfmc_listsubscribers.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_SUBSCRIBERS (
    SUBSCRIBER_ID       VARCHAR,
    SUBSCRIBER_KEY      VARCHAR,
    EMAIL_ADDRESS       VARCHAR,
    SUBSCRIBER_STATUS   VARCHAR,
    DATE_JOINED         VARCHAR,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_SUBSCRIBERS (SUBSCRIBER_ID, SUBSCRIBER_KEY, EMAIL_ADDRESS, SUBSCRIBER_STATUS, DATE_JOINED)
FROM (
    SELECT $1, $2, $3, $4, $5
    FROM @STG_HCP_LANDING/sfmc_subscribers.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_SENT (
    JOB_ID          VARCHAR,
    LIST_ID         VARCHAR,
    BATCH_ID        VARCHAR,
    SUBSCRIBER_ID   VARCHAR,
    SUBSCRIBER_KEY  VARCHAR,
    EVENT_DATE      TIMESTAMP_NTZ,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_SENT (JOB_ID, LIST_ID, BATCH_ID, SUBSCRIBER_ID, SUBSCRIBER_KEY, EVENT_DATE)
FROM (
    SELECT $1, $2, $3, $4, $5, TO_TIMESTAMP_NTZ($6)
    FROM @STG_HCP_LANDING/sfmc_sent.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_BOUNCE (
    JOB_ID              VARCHAR,
    SUBSCRIBER_KEY      VARCHAR,
    EVENT_DATE          TIMESTAMP_NTZ,
    BOUNCE_CATEGORY     VARCHAR,
    BOUNCE_SUBCATEGORY  VARCHAR,
    SMTP_CODE           VARCHAR,
    SMTP_BOUNCE_REASON  VARCHAR,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_BOUNCE
    (JOB_ID, SUBSCRIBER_KEY, EVENT_DATE, BOUNCE_CATEGORY, BOUNCE_SUBCATEGORY, SMTP_CODE, SMTP_BOUNCE_REASON)
FROM (
    SELECT $1, $2, TO_TIMESTAMP_NTZ($3), $4, $5, $6, $7
    FROM @STG_HCP_LANDING/sfmc_bounce.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_UNSUBSCRIBE (
    SUBSCRIBER_KEY   VARCHAR,
    UNSUB_DATE_UTC   TIMESTAMP_NTZ,
    UNSUB_REASON     VARCHAR,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_UNSUBSCRIBE (SUBSCRIBER_KEY, UNSUB_DATE_UTC, UNSUB_REASON)
FROM (
    SELECT $1, TO_TIMESTAMP_NTZ($2), $3
    FROM @STG_HCP_LANDING/sfmc_unsubscribe.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_OPEN (
    JOB_ID          VARCHAR,
    SUBSCRIBER_KEY  VARCHAR,
    EVENT_DATE      TIMESTAMP_NTZ,
    IS_UNIQUE       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_OPEN (JOB_ID, SUBSCRIBER_KEY, EVENT_DATE, IS_UNIQUE)
FROM (
    SELECT $1, $2, TO_TIMESTAMP_NTZ($3), $4
    FROM @STG_HCP_LANDING/sfmc_open.csv
)
ON_ERROR = 'SKIP_FILE';

CREATE TABLE IF NOT EXISTS RAW_CLICK (
    JOB_ID          VARCHAR,
    SUBSCRIBER_KEY  VARCHAR,
    EVENT_DATE      TIMESTAMP_NTZ,
    IS_UNIQUE       VARCHAR,
    LINK_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO RAW_CLICK (JOB_ID, SUBSCRIBER_KEY, EVENT_DATE, IS_UNIQUE, LINK_NAME)
FROM (
    SELECT $1, $2, TO_TIMESTAMP_NTZ($3), $4, $5
    FROM @STG_HCP_LANDING/sfmc_click.csv
)
ON_ERROR = 'SKIP_FILE';

INSERT INTO FILE_LOAD_AUDIT (SOURCE_FILE, TARGET_TABLE, ROWS_LOADED, LOAD_STATUS)
SELECT 'hcp_subscribers.csv', 'RAW_HCP_SUBSCRIBER', COUNT(*), 'SUCCESS' FROM RAW_HCP_SUBSCRIBER
UNION ALL
SELECT 'sfmc_automation_studio_activity_log.csv', 'RAW_AUTOMATION_ACTIVITY_LOG', COUNT(*), 'SUCCESS' FROM RAW_AUTOMATION_ACTIVITY_LOG
UNION ALL
SELECT 'sfmc_journey_status.csv', 'RAW_JOURNEY_STATUS', COUNT(*), 'SUCCESS' FROM RAW_JOURNEY_STATUS
UNION ALL
SELECT 'sfmc_listsubscribers.csv', 'RAW_LISTSUBSCRIBERS', COUNT(*), 'SUCCESS' FROM RAW_LISTSUBSCRIBERS
UNION ALL
SELECT 'sfmc_subscribers.csv', 'RAW_SUBSCRIBERS', COUNT(*), 'SUCCESS' FROM RAW_SUBSCRIBERS
UNION ALL
SELECT 'sfmc_sent.csv', 'RAW_SENT', COUNT(*), 'SUCCESS' FROM RAW_SENT
UNION ALL
SELECT 'sfmc_bounce.csv', 'RAW_BOUNCE', COUNT(*), 'SUCCESS' FROM RAW_BOUNCE
UNION ALL
SELECT 'sfmc_unsubscribe.csv', 'RAW_UNSUBSCRIBE', COUNT(*), 'SUCCESS' FROM RAW_UNSUBSCRIBE
UNION ALL
SELECT 'sfmc_open.csv', 'RAW_OPEN', COUNT(*), 'SUCCESS' FROM RAW_OPEN
UNION ALL
SELECT 'sfmc_click.csv', 'RAW_CLICK', COUNT(*), 'SUCCESS' FROM RAW_CLICK;
