-- governance_policies.sql

USE DATABASE CEDP_HCP_OUTREACH;
USE WAREHOUSE CEDP_ETL_WH;


-- 1. Roles

CREATE ROLE IF NOT EXISTS PII_VIEWER;
CREATE ROLE IF NOT EXISTS BRAND_OPS_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;


-- 2. Masking policies -- applied once, held across Dynamic Table refreshes

USE SCHEMA BRONZE;

CREATE OR REPLACE MASKING POLICY MASK_NPI AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PII_VIEWER', 'BRAND_OPS_ADMIN', 'ACCOUNTADMIN')
         THEN val
         ELSE 'XXXXXXXXXX' || RIGHT(val, 4)
    END;

CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (val VARCHAR) RETURNS VARCHAR ->
    CASE WHEN CURRENT_ROLE() IN ('PII_VIEWER', 'BRAND_OPS_ADMIN', 'ACCOUNTADMIN')
         THEN val
         ELSE REGEXP_REPLACE(val, '^(.).*(@.*)$', '\\1***\\2')
    END;

ALTER TABLE RAW_HCP_SUBSCRIBER MODIFY COLUMN NPI SET MASKING POLICY MASK_NPI;
ALTER TABLE RAW_SUBSCRIBERS MODIFY COLUMN EMAIL_ADDRESS SET MASKING POLICY MASK_EMAIL;

-- Applied to the Silver DYNAMIC TABLE directly -- this is a one-time
-- statement now, not a step that has to be repeated after every refresh.
ALTER TABLE SILVER.SUBSCRIBER MODIFY COLUMN NPI SET MASKING POLICY BRONZE.MASK_NPI;


-- 3. Row access policy -- Business Unit / Brand scoping

CREATE TABLE IF NOT EXISTS BRONZE.ROLE_BU_GRANTS (
    ROLE_NAME VARCHAR, BUSINESS_UNIT_ID VARCHAR
);
INSERT INTO BRONZE.ROLE_BU_GRANTS VALUES ('BRAND_OPS_ADMIN', 'BU_PHARMA');

CREATE OR REPLACE ROW ACCESS POLICY BRONZE.RAP_BUSINESS_UNIT AS (bu_id VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN'
    OR EXISTS (SELECT 1 FROM BRONZE.ROLE_BU_GRANTS g WHERE g.ROLE_NAME = CURRENT_ROLE() AND g.BUSINESS_UNIT_ID = bu_id);

ALTER TABLE SILVER.SUBSCRIBER ADD ROW ACCESS POLICY BRONZE.RAP_BUSINESS_UNIT ON (BUSINESS_UNIT_ID);


-- 4. Classification tags

CREATE TAG IF NOT EXISTS BRONZE.DATA_CLASSIFICATION;
ALTER TABLE SILVER.SUBSCRIBER MODIFY COLUMN NPI SET TAG BRONZE.DATA_CLASSIFICATION = 'PII';


-- 5. Retention / anonymization

CREATE OR REPLACE PROCEDURE BRONZE.SP_ANONYMIZE_EXPIRED_CONTACTS(RETENTION_DAYS INTEGER)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE BRONZE.RAW_HCP_SUBSCRIBER
    SET NPI = 'ANONYMIZED'
    WHERE SUBSCRIBER_KEY IN (
        SELECT SUBSCRIBER_KEY FROM BRONZE.RAW_SUBSCRIBERS WHERE SUBSCRIBER_STATUS = 'Unsubscribed'
    );
    RETURN 'anonymization pass complete -- SILVER.SUBSCRIBER will pick this up on its next refresh';
END;
$$;

CREATE OR REPLACE TASK BRONZE.TASK_ANONYMIZE_EXPIRED_CONTACTS
    WAREHOUSE = CEDP_ETL_WH
    SCHEDULE = 'USING CRON 0 3 1 * * UTC'
AS
    CALL BRONZE.SP_ANONYMIZE_EXPIRED_CONTACTS(400);
-- ALTER TASK BRONZE.TASK_ANONYMIZE_EXPIRED_CONTACTS RESUME;
