-- observability.sql


USE DATABASE CEDP_HCP_OUTREACH;
USE WAREHOUSE CEDP_ETL_WH;


-- 1. Bronze ingest freshness -- did the daily load actually happen

SELECT
    TARGET_TABLE,
    MAX(LOAD_TIMESTAMP) AS LAST_LOADED,
    DATEDIFF('hour', MAX(LOAD_TIMESTAMP), CURRENT_TIMESTAMP()) AS HOURS_SINCE_LOAD,
    CASE WHEN DATEDIFF('hour', MAX(LOAD_TIMESTAMP), CURRENT_TIMESTAMP()) > 24
         THEN 'BREACH' ELSE 'OK' END AS FRESHNESS_STATUS
FROM BRONZE.FILE_LOAD_AUDIT
GROUP BY TARGET_TABLE
ORDER BY HOURS_SINCE_LOAD DESC;


-- 2. Dynamic Table refresh health 

SELECT
    NAME AS DYNAMIC_TABLE_NAME,
    TARGET_LAG_SEC,
    MEAN_LAG_SEC,
    MAX_LAG_SEC,
    CASE WHEN MAX_LAG_SEC > TARGET_LAG_SEC * 2 THEN 'BREACH' ELSE 'OK' END AS LAG_STATUS
FROM (
    SELECT
        QUALIFIED_NAME AS NAME,
        TARGET_LAG_SEC,
        AVG(DATEDIFF('second', DATA_TIMESTAMP, REFRESH_END_TIME)) AS MEAN_LAG_SEC,
        MAX(DATEDIFF('second', DATA_TIMESTAMP, REFRESH_END_TIME)) AS MAX_LAG_SEC
    FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY
    WHERE QUALIFIED_NAME ILIKE 'CEDP_HCP_OUTREACH.%'
      AND REFRESH_START_TIME > DATEADD('day', -7, CURRENT_TIMESTAMP())
    GROUP BY QUALIFIED_NAME, TARGET_LAG_SEC
);


-- 3. Quality SLA 

SELECT
    FROM_CHECKPOINT_NAME,
    TO_CHECKPOINT_NAME,
    UNEXPLAINED_PCT,
    CASE WHEN UNEXPLAINED_PCT > 5 THEN 'SLA_BREACH' ELSE 'OK' END AS QUALITY_STATUS
FROM SEMANTIC.VW_FUNNEL_RECONCILIATION
ORDER BY UNEXPLAINED_PCT DESC;


-- 4. Cross-check against Automation Studio's own reported counts

SELECT
    'Consent & DNC filter' AS CHECK_NAME,
    (SELECT COUNT(*) FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT WHERE CHECKPOINT_KEY = 2 AND EXCLUDED_FLAG) AS RECOMPUTED_COUNT,
    (SELECT EXCLUDED_COUNT FROM SILVER.AUTOMATION_ACTIVITY_LOG WHERE ACTIVITY_NAME = 'Consent_DNC_Filter') AS AUTOMATION_STUDIO_REPORTED_COUNT

UNION ALL

SELECT 'Specialty eligibility filter',
    (SELECT COUNT(*) FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT WHERE CHECKPOINT_KEY = 3 AND EXCLUDED_FLAG),
    (SELECT EXCLUDED_COUNT FROM SILVER.AUTOMATION_ACTIVITY_LOG WHERE ACTIVITY_NAME = 'Specialty_Eligibility_Filter')

UNION ALL

SELECT 'Tier / engagement filter',
    (SELECT COUNT(*) FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT WHERE CHECKPOINT_KEY = 4 AND EXCLUDED_FLAG),
    (SELECT EXCLUDED_COUNT FROM SILVER.AUTOMATION_ACTIVITY_LOG WHERE ACTIVITY_NAME = 'Tier_Engagement_Filter')

UNION ALL

SELECT 'Final send-ready filter',
    (SELECT COUNT(*) FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT WHERE CHECKPOINT_KEY = 5 AND EXCLUDED_FLAG),
    (SELECT EXCLUDED_COUNT FROM SILVER.AUTOMATION_ACTIVITY_LOG WHERE ACTIVITY_NAME = 'Final_Send_Ready_Filter');


-- 5. Bronze-to-Gold row reconciliation 

SELECT
    (SELECT COUNT(*) FROM BRONZE.RAW_HCP_SUBSCRIBER) AS BRONZE_ROW_COUNT,
    (SELECT COUNT(*) FROM SILVER.SUBSCRIBER) AS SILVER_ROW_COUNT,
    (SELECT COUNT(*) FROM GOLD.DIM_SUBSCRIBER WHERE SUBSCRIBER_SK != -1) AS GOLD_ROW_COUNT;


-- 6. Governance policy attachment 

SELECT
    REF_ENTITY_NAME AS TABLE_NAME,
    REF_COLUMN_NAME AS COLUMN_NAME,
    POLICY_NAME
FROM TABLE(
    CEDP_HCP_OUTREACH.INFORMATION_SCHEMA.POLICY_REFERENCES(
        REF_ENTITY_NAME => 'CEDP_HCP_OUTREACH.SILVER.SUBSCRIBER',
        REF_ENTITY_DOMAIN => 'TABLE'
    )
);


-- 7. Usage tracking 

SELECT
    QUERY_TEXT,
    USER_NAME,
    START_TIME,
    TOTAL_ELAPSED_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT ILIKE '%SEMANTIC.VW_%'
  AND START_TIME > DATEADD('day', -30, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC
LIMIT 200;


-- 8. Retirement gate 

-- Example: checking whether FACT_PROGRAM_RECONCILIATION (v1.0.0, dropped
-- in v2.0.0) had any remaining queries before it was actually removed.
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
-- WHERE QUERY_TEXT ILIKE '%FACT_PROGRAM_RECONCILIATION%'
--   AND START_TIME > DATEADD('day', -30, CURRENT_TIMESTAMP());
