-- reconciliation.sql
USE DATABASE CEDP_HCP_OUTREACH;
USE SCHEMA GOLD;
USE WAREHOUSE CEDP_ETL_WH;

CREATE OR REPLACE TEMPORARY TABLE CHECKPOINT_SUMMARY AS
SELECT
    dc.CHECKPOINT_KEY,
    dc.STEP_SEQUENCE,
    dc.CHECKPOINT_NAME,
    COUNT(*) AS TOTAL_AT_CHECKPOINT,
    SUM(CASE WHEN f.EXCLUDED_FLAG OR f.FAILED_FLAG THEN 1 ELSE 0 END) AS EXPLAINED_LOSS
FROM FACT_SUBSCRIBER_CHECKPOINT f
JOIN DIM_CHECKPOINT dc ON dc.CHECKPOINT_KEY = f.CHECKPOINT_KEY
WHERE dc.CHECKPOINT_KEY != -1
GROUP BY dc.CHECKPOINT_KEY, dc.STEP_SEQUENCE, dc.CHECKPOINT_NAME;

CREATE OR REPLACE TABLE FACT_FUNNEL_RECONCILIATION AS
SELECT
    a.CHECKPOINT_KEY   AS FROM_CHECKPOINT_KEY,
    b.CHECKPOINT_KEY   AS TO_CHECKPOINT_KEY,
    a.CHECKPOINT_NAME  AS FROM_CHECKPOINT_NAME,
    b.CHECKPOINT_NAME  AS TO_CHECKPOINT_NAME,
    a.TOTAL_AT_CHECKPOINT AS INPUT_COUNT,
    b.TOTAL_AT_CHECKPOINT AS OUTPUT_COUNT,
    a.TOTAL_AT_CHECKPOINT - b.TOTAL_AT_CHECKPOINT AS RAW_DIFFERENCE,
    a.EXPLAINED_LOSS AS EXPLAINED_DIFFERENCE,
    (a.TOTAL_AT_CHECKPOINT - b.TOTAL_AT_CHECKPOINT) - a.EXPLAINED_LOSS AS UNEXPLAINED_DIFFERENCE,
    ROUND(
        100.0 * ((a.TOTAL_AT_CHECKPOINT - b.TOTAL_AT_CHECKPOINT) - a.EXPLAINED_LOSS)
        / NULLIF(a.TOTAL_AT_CHECKPOINT, 0), 2
    ) AS UNEXPLAINED_PCT,
    CURRENT_TIMESTAMP() AS COMPUTED_TIMESTAMP
FROM CHECKPOINT_SUMMARY a
JOIN CHECKPOINT_SUMMARY b ON b.STEP_SEQUENCE = a.STEP_SEQUENCE + 1
ORDER BY a.STEP_SEQUENCE;


SELECT * FROM FACT_FUNNEL_RECONCILIATION WHERE UNEXPLAINED_DIFFERENCE != 0;
