-- semantic_views.sql


USE DATABASE CEDP_HCP_OUTREACH;
USE SCHEMA SEMANTIC;
USE WAREHOUSE CEDP_ETL_WH;


-- Funnel by stage

CREATE OR REPLACE VIEW VW_HCP_FUNNEL AS
SELECT
    dc.STEP_SEQUENCE,
    dc.CHECKPOINT_NAME,
    dc.BUILT_FROM,
    COUNT(*) AS HCPS_AT_CHECKPOINT,
    SUM(CASE WHEN f.EXCLUDED_FLAG THEN 1 ELSE 0 END) AS EXCLUDED,
    SUM(CASE WHEN f.FAILED_FLAG THEN 1 ELSE 0 END) AS FAILED
FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT f
JOIN GOLD.DIM_CHECKPOINT dc ON dc.CHECKPOINT_KEY = f.CHECKPOINT_KEY
GROUP BY dc.STEP_SEQUENCE, dc.CHECKPOINT_NAME, dc.BUILT_FROM
ORDER BY dc.STEP_SEQUENCE;


-- Where and why HCPs were lost

CREATE OR REPLACE VIEW VW_WHERE_AND_WHY_LOST AS
SELECT
    dc.CHECKPOINT_NAME,
    dr.REASON_DESCRIPTION,
    dr.RESPONSIBLE_PARTY,
    dr.RESPONSIBLE_PARTY_TYPE,
    CASE WHEN dr.IS_INTENTIONAL THEN 'Intentional' ELSE 'Unexpected' END AS LOSS_CLASSIFICATION,
    COUNT(*) AS HCPS_AFFECTED
FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT f
JOIN GOLD.DIM_CHECKPOINT dc ON dc.CHECKPOINT_KEY = f.CHECKPOINT_KEY
JOIN GOLD.DIM_REASON dr ON dr.REASON_KEY = f.REASON_KEY
WHERE (f.EXCLUDED_FLAG OR f.FAILED_FLAG) AND dr.REASON_KEY != -1
GROUP BY dc.CHECKPOINT_NAME, dr.REASON_DESCRIPTION, dr.RESPONSIBLE_PARTY, dr.RESPONSIBLE_PARTY_TYPE, dr.IS_INTENTIONAL
ORDER BY HCPS_AFFECTED DESC;

-- Loss grouped by which team owns the fix

CREATE OR REPLACE VIEW VW_LOSS_ROOT_CAUSE_CATEGORY AS
SELECT
    dr.RESPONSIBLE_PARTY_TYPE,
    COUNT(*) AS HCPS_AFFECTED
FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT f
JOIN GOLD.DIM_REASON dr ON dr.REASON_KEY = f.REASON_KEY
WHERE (f.EXCLUDED_FLAG OR f.FAILED_FLAG) AND dr.REASON_KEY != -1
GROUP BY dr.RESPONSIBLE_PARTY_TYPE
ORDER BY HCPS_AFFECTED DESC;

-- Anyone who dropped out with NO matching reason 
CREATE OR REPLACE VIEW VW_UNKNOWN_UNRECONCILED_POPULATION AS
SELECT
    dc.CHECKPOINT_NAME,
    COUNT(*) AS UNKNOWN_HCP_COUNT
FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT f
JOIN GOLD.DIM_CHECKPOINT dc ON dc.CHECKPOINT_KEY = f.CHECKPOINT_KEY
WHERE (f.EXCLUDED_FLAG OR f.FAILED_FLAG) AND f.REASON_KEY = -1
GROUP BY dc.CHECKPOINT_NAME;

-- Full lineage for one HCP -- what happened to them, stage by stage

CREATE OR REPLACE VIEW VW_HCP_LINEAGE AS
SELECT
    ds.SUBSCRIBER_KEY,
    dc.STEP_SEQUENCE,
    dc.CHECKPOINT_NAME,
    f.EVENT_STATUS,
    dr.REASON_DESCRIPTION,
    dr.RESPONSIBLE_PARTY
FROM GOLD.FACT_SUBSCRIBER_CHECKPOINT f
JOIN GOLD.DIM_SUBSCRIBER ds ON ds.SUBSCRIBER_SK = f.SUBSCRIBER_SK
JOIN GOLD.DIM_CHECKPOINT dc ON dc.CHECKPOINT_KEY = f.CHECKPOINT_KEY
LEFT JOIN GOLD.DIM_REASON dr ON dr.REASON_KEY = f.REASON_KEY
ORDER BY ds.SUBSCRIBER_KEY, dc.STEP_SEQUENCE;

-- Plain-English executive summary, one row per checkpoint transition

CREATE OR REPLACE VIEW VW_EXECUTIVE_SUMMARY AS
SELECT
    FROM_CHECKPOINT_NAME || ' started with ' || INPUT_COUNT || ' HCPs, passed ' || OUTPUT_COUNT ||
    ' through, explained the loss of ' || EXPLAINED_DIFFERENCE ||
    ' via known policy/consent reasons, and left ' || UNEXPLAINED_DIFFERENCE ||
    ' (' || UNEXPLAINED_PCT || '%) unexplained -- ' ||
    CASE WHEN UNEXPLAINED_PCT > 5 THEN 'this exceeds the quality SLA and needs investigation.'
         ELSE 'this is within the acceptable quality SLA.' END AS SUMMARY_SENTENCE
FROM GOLD.FACT_FUNNEL_RECONCILIATION
ORDER BY FROM_CHECKPOINT_KEY;
