-- setup.sql
-- Sets up the database, schemas, warehouse and stage for the HCP Subscriber

CREATE WAREHOUSE IF NOT EXISTS CEDP_ETL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CEDP_ETL_WH;

CREATE DATABASE IF NOT EXISTS CEDP_HCP_OUTREACH;

CREATE SCHEMA IF NOT EXISTS CEDP_HCP_OUTREACH.BRONZE;
CREATE SCHEMA IF NOT EXISTS CEDP_HCP_OUTREACH.SILVER;
CREATE SCHEMA IF NOT EXISTS CEDP_HCP_OUTREACH.GOLD;
CREATE SCHEMA IF NOT EXISTS CEDP_HCP_OUTREACH.SEMANTIC;

USE SCHEMA CEDP_HCP_OUTREACH.BRONZE;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV
    TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS STG_HCP_LANDING FILE_FORMAT = FF_CSV;


CREATE OR REPLACE TASK BRONZE.TASK_LOAD_HCP_FILES
    WAREHOUSE = CEDP_ETL_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'  -- 1 hour before Automation Studio's 07:00 UTC run
AS
    EXECUTE IMMEDIATE $$
        BEGIN
            COPY INTO BRONZE.RAW_HCP_SUBSCRIBER (SUBSCRIBER_KEY, NPI, FIRST_NAME, LAST_NAME, SPECIALTY,
                HCP_TIER, LICENSE_STATE, INSTITUTION_NAME, CONSENT_STATUS, DO_NOT_CONTACT_FLAG,
                BUSINESS_UNIT_ID, BRAND_ID, IMPORT_DATE, SOURCE_FILE_NAME)
            FROM (
                SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13, METADATA$FILENAME
                FROM @BRONZE.STG_HCP_LANDING/hcp_subscribers.csv
            )
            ON_ERROR = 'SKIP_FILE';
            -- repeat one COPY INTO block per source file, same pattern as
            -- 01_bronze/bronze_ingest.sql from the earlier package
            RETURN 'bronze load complete';
        END;
    $$;
-- ALTER TASK BRONZE.TASK_LOAD_HCP_FILES RESUME;




CREATE TABLE IF NOT EXISTS FILE_LOAD_AUDIT (
    LOAD_AUDIT_ID   VARCHAR DEFAULT UUID_STRING(),
    SOURCE_FILE     VARCHAR,
    TARGET_TABLE    VARCHAR,
    ROWS_LOADED     NUMBER,
    LOAD_STATUS     VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);




