USE DATABASE CEDP_HCP_OUTREACH;
USE SCHEMA SILVER;
USE WAREHOUSE CEDP_ETL_WH;


-- SUBSCRIBER

CREATE OR REPLACE DYNAMIC TABLE SUBSCRIBER
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT
    de.SUBSCRIBER_KEY,
    de.NPI,
    de.FIRST_NAME,
    de.LAST_NAME,
    de.SPECIALTY,
    de.HCP_TIER,
    de.LICENSE_STATE,
    de.INSTITUTION_NAME,
    de.CONSENT_STATUS,
    CASE WHEN UPPER(de.DO_NOT_CONTACT_FLAG) = 'TRUE' THEN TRUE ELSE FALSE END AS DO_NOT_CONTACT_FLAG,
    de.BUSINESS_UNIT_ID,
    de.BRAND_ID,
    COALESCE(subs.SUBSCRIBER_STATUS, 'Active') AS SUBSCRIBER_STATUS
FROM BRONZE.RAW_HCP_SUBSCRIBER de
LEFT JOIN BRONZE.RAW_SUBSCRIBERS subs
    ON de.SUBSCRIBER_KEY = subs.SUBSCRIBER_KEY;


-- AUTOMATION_ACTIVITY_LOG

CREATE OR REPLACE DYNAMIC TABLE AUTOMATION_ACTIVITY_LOG
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT AUTOMATION_NAME, ACTIVITY_NAME, ACTIVITY_TYPE, TARGET_DATA_EXTENSION,
       SQL_TEXT, RUN_ID, INPUT_COUNT, OUTPUT_COUNT, EXCLUDED_COUNT, RUN_TIMESTAMP
FROM BRONZE.RAW_AUTOMATION_ACTIVITY_LOG;


-- JOURNEY_STATUS

CREATE OR REPLACE DYNAMIC TABLE JOURNEY_STATUS
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT SUBSCRIBER_KEY, JOURNEY_NAME, JOURNEY_VERSION, JOURNEY_STATUS, ENTRY_TIMESTAMP
FROM BRONZE.RAW_JOURNEY_STATUS;


-- SUPPRESSION_STATE

CREATE OR REPLACE DYNAMIC TABLE SUPPRESSION_STATE
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT SUBSCRIBER_KEY, LIST_ID, LIST_STATUS, STATUS_REASON
FROM BRONZE.RAW_LISTSUBSCRIBERS;


-- OUTREACH_ATTEMPT

CREATE OR REPLACE DYNAMIC TABLE OUTREACH_ATTEMPT
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT JOB_ID, SUBSCRIBER_KEY, 'EMAIL' AS CHANNEL, EVENT_DATE AS ATTEMPT_TIMESTAMP
FROM BRONZE.RAW_SENT;


-- OUTREACH_EVENT

CREATE OR REPLACE DYNAMIC TABLE OUTREACH_EVENT
    TARGET_LAG = '30 minutes'
    WAREHOUSE = CEDP_ETL_WH
AS
SELECT SUBSCRIBER_KEY, 'FAILED' AS EVENT_TYPE, BOUNCE_CATEGORY AS EVENT_DETAIL, EVENT_DATE AS EVENT_TIMESTAMP
FROM BRONZE.RAW_BOUNCE

UNION ALL

SELECT SUBSCRIBER_KEY, 'OPTED_OUT', UNSUB_REASON, UNSUB_DATE_UTC
FROM BRONZE.RAW_UNSUBSCRIBE

UNION ALL

SELECT SUBSCRIBER_KEY, 'OPENED', NULL, EVENT_DATE
FROM BRONZE.RAW_OPEN

UNION ALL

SELECT SUBSCRIBER_KEY, 'CLICKED', LINK_NAME, EVENT_DATE
FROM BRONZE.RAW_CLICK

UNION ALL

SELECT sent.SUBSCRIBER_KEY, 'REACHED', NULL, sent.EVENT_DATE
FROM BRONZE.RAW_SENT sent
WHERE NOT EXISTS (
    SELECT 1 FROM BRONZE.RAW_BOUNCE b WHERE b.SUBSCRIBER_KEY = sent.SUBSCRIBER_KEY
);
